
# Autogenerated makefile
# android/android-emugl/host/libs/libOpenglRender/vulkan-registry/xml/genvk.py -registry android/android-emugl/host/libs/libOpenglRender/vulkan-registry/xml/vk.xml cereal -o android/android-emugl/host/libs/libOpenglRender/vulkan/cereal
# Please do not modify directly;
# re-run android/scripts/generate-vulkan-sources.sh,
# or directly from Python by defining:
# VULKAN_REGISTRY_XML_DIR : Directory containing genvk.py and vk.xml
# CEREAL_OUTPUT_DIR: Where to put the generated sources.
# python3 $VULKAN_REGISTRY_XML_DIR/genvk.py -registry $VULKAN_REGISTRY_XML_DIR/vk.xml cereal -o $CEREAL_OUTPUT_DIR

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := OpenglRender_vulkan_cereal
LOCAL_SRC_FILES := \
    common/goldfish_vk_extension_structs.cpp \
    common/goldfish_vk_marshaling.cpp \
    common/goldfish_vk_testing.cpp \
    common/goldfish_vk_deepcopy.cpp \
    common/goldfish_vk_handlemap.cpp \
    common/goldfish_vk_dispatch.cpp \
    common/goldfish_vk_transform.cpp \
    common/goldfish_vk_unbox.cpp \
    common/goldfish_vk_baseprotoconversion.cpp

LOCAL_C_INCLUDES  := \
    $(TOP_SRC_ROOT)/android-emu \
    $(TOP_SRC_ROOT)/android-emugl/host/libs/libOpenglRender/vulkan/cereal \
    $(TOP_SRC_ROOT)/android-emugl/host/libs/libOpenglRender/vulkan \
    $(TOP_SRC_ROOT)/android-emugl/host/include/vulkan
LOCAL_CFLAGS := -D__STDC_LIMIT_MACROS=1 -DEMUGL_BUILD=1
LOCAL_STATIC_LIBRARIES  := 
LOCAL_SHARED_LIBRARIES  :=
LOCAL_LDFLAGS :=
LOCAL_LDLIBS  :=

include $(BUILD_STATIC_LIBRARY)
